### PR TITLE
copy cheats from CUSA00265 to CUSA00744

### PR DESCRIPTION
**Pull request by W-i-n-7**
Minecraft EU to US version

### CODE REVIEW

**Comment by kmeps4** [comment]
Needs Review. @Tribb

**Comment by Tribb** [comment]
&lt;?xml version=\&quot;1.0\&quot; encoding=\&quot;utf-16\&quot;?&gt;
&lt;Trainer xmlns:xsd=\&quot;http://www.w3.org/2001/XMLSchema\&quot; xmlns:xsi=\&quot;http://www.w3.org/2001/XMLSchema-instance\&quot; Game=\&quot;Minecraft\&quot; Moder=\&quot;DeathRGH\&quot; Cusa=\&quot;CUSA00265\&quot; Version=\&quot;01.00\&quot; Process=\&quot;eboot.bin\&quot;&gt;
as you can see the cheat uses old outdated tools and is still for CUSA00265 so please extract and fix it properly before upload

**Comment by W-i-n-7** [comment]
@Tribb i changed the CUSA in the xml
i hope this is enough otherwise you can close the pull request

**Comment by Tribb** [comment]
if you look in Apollo Github you will find tools to extract the MC4 here https://github.com/bucanero/save-decrypters/tree/master/mc4-cheat-decrypter   when extracted its in a broken shn format so just fix it and PR the .shn, No need for xml this way

**Pull request closed without merging**
