### PR TITLE
Like a Dragon Infinite Wealth 01.13 trainers

### PR DESCRIPTION
**Pull request by Pharaoh2k**
Tested and working well. No conflicts.
Please merge.
Thanks :-)

### CODE REVIEW

**Comment by kmeps4** [comment]
Thx 😀

**Comment by greenuns** [comment]
wanna say thank you for this. will there be anymore cheats for this game? perhaps an XP multiplier?

**Comment by Pharaoh2k** [comment]
Yes. All the below cheats are already included. Please feel free to come to the ps4trainer discord server #shns-public channel for details on how to privately get it before it gets publicly released to the repo.


efWRp1f

**Comment by greenuns** [comment]
awesome!

**Pull request merged**
